version: "3.4"
services:
  app:
    build: .
    network_mode: "host"
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_PASSWORD=12345
      - POSTGRES_USER=king_roland
      - POSTGRES_DB=shipping
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    network_mode: "host"
    environment:
      - POSTGRES_PASSWORD=12345
      - POSTGRES_USER=king_roland
      - POSTGRES_DB=shipping
    volumes:
      - ./db:/docker-entrypoint-initdb.d
