version: "3.4"
services:
  app:
    build:
      context: .
      target: app
    ports:
      - 5000:5000
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_PASSWORD=12345
      - POSTGRES_USER=king_roland
      - POSTGRES_DB=shipping
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=12345
      - POSTGRES_USER=king_roland
      - POSTGRES_DB=shipping
    volumes:
      - ./db:/docker-entrypoint-initdb.d
